# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.error_detail_metadata import ErrorDetailMetadata  # noqa: F401,E501
from swagger_server import util


class AllOfErrorDetailMeta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, vendor_error_code: str=None, vendor: str=None):  # noqa: E501
        """AllOfErrorDetailMeta - a model defined in Swagger

        :param vendor_error_code: The vendor_error_code of this AllOfErrorDetailMeta.  # noqa: E501
        :type vendor_error_code: str
        :param vendor: The vendor of this AllOfErrorDetailMeta.  # noqa: E501
        :type vendor: str
        """
        self.swagger_types = {
            'vendor_error_code': str,
            'vendor': str
        }

        self.attribute_map = {
            'vendor_error_code': 'vendorErrorCode',
            'vendor': 'vendor'
        }
        self._vendor_error_code = vendor_error_code
        self._vendor = vendor

    @classmethod
    def from_dict(cls, dikt) -> 'AllOfErrorDetailMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOfErrorDetailMeta of this AllOfErrorDetailMeta.  # noqa: E501
        :rtype: AllOfErrorDetailMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vendor_error_code(self) -> str:
        """Gets the vendor_error_code of this AllOfErrorDetailMeta.

        The error code specific to vendor  # noqa: E501

        :return: The vendor_error_code of this AllOfErrorDetailMeta.
        :rtype: str
        """
        return self._vendor_error_code

    @vendor_error_code.setter
    def vendor_error_code(self, vendor_error_code: str):
        """Sets the vendor_error_code of this AllOfErrorDetailMeta.

        The error code specific to vendor  # noqa: E501

        :param vendor_error_code: The vendor_error_code of this AllOfErrorDetailMeta.
        :type vendor_error_code: str
        """

        self._vendor_error_code = vendor_error_code

    @property
    def vendor(self) -> str:
        """Gets the vendor of this AllOfErrorDetailMeta.

        The string that describes the vendor  # noqa: E501

        :return: The vendor of this AllOfErrorDetailMeta.
        :rtype: str
        """
        return self._vendor

    @vendor.setter
    def vendor(self, vendor: str):
        """Sets the vendor of this AllOfErrorDetailMeta.

        The string that describes the vendor  # noqa: E501

        :param vendor: The vendor of this AllOfErrorDetailMeta.
        :type vendor: str
        """

        self._vendor = vendor
