# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HttpErrorResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: int=None, detail: str=None, instance: str=None):  # noqa: E501
        """HttpErrorResponse - a model defined in Swagger

        :param status: The status of this HttpErrorResponse.  # noqa: E501
        :type status: int
        :param detail: The detail of this HttpErrorResponse.  # noqa: E501
        :type detail: str
        :param instance: The instance of this HttpErrorResponse.  # noqa: E501
        :type instance: str
        """
        self.swagger_types = {
            'status': int,
            'detail': str,
            'instance': str
        }

        self.attribute_map = {
            'status': 'status',
            'detail': 'detail',
            'instance': 'instance'
        }
        self._status = status
        self._detail = detail
        self._instance = instance

    @classmethod
    def from_dict(cls, dikt) -> 'HttpErrorResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HttpErrorResponse of this HttpErrorResponse.  # noqa: E501
        :rtype: HttpErrorResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this HttpErrorResponse.

        The statusCode of HTTP errors reported back to the client  # noqa: E501

        :return: The status of this HttpErrorResponse.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this HttpErrorResponse.

        The statusCode of HTTP errors reported back to the client  # noqa: E501

        :param status: The status of this HttpErrorResponse.
        :type status: int
        """

        self._status = status

    @property
    def detail(self) -> str:
        """Gets the detail of this HttpErrorResponse.

        The detail of HTTP errors reported back to the client  # noqa: E501

        :return: The detail of this HttpErrorResponse.
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail: str):
        """Sets the detail of this HttpErrorResponse.

        The detail of HTTP errors reported back to the client  # noqa: E501

        :param detail: The detail of this HttpErrorResponse.
        :type detail: str
        """

        self._detail = detail

    @property
    def instance(self) -> str:
        """Gets the instance of this HttpErrorResponse.

        The URI response reported back to the client  # noqa: E501

        :return: The instance of this HttpErrorResponse.
        :rtype: str
        """
        return self._instance

    @instance.setter
    def instance(self, instance: str):
        """Sets the instance of this HttpErrorResponse.

        The URI response reported back to the client  # noqa: E501

        :param instance: The instance of this HttpErrorResponse.
        :type instance: str
        """

        self._instance = instance
