# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Reason(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reason: str=None):  # noqa: E501
        """Reason - a model defined in Swagger

        :param reason: The reason of this Reason.  # noqa: E501
        :type reason: str
        """
        self.swagger_types = {
            'reason': str
        }

        self.attribute_map = {
            'reason': 'reason'
        }
        self._reason = reason

    @classmethod
    def from_dict(cls, dikt) -> 'Reason':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Reason of this Reason.  # noqa: E501
        :rtype: Reason
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reason(self) -> str:
        """Gets the reason of this Reason.

        Defines a string object that is used for reason  # noqa: E501

        :return: The reason of this Reason.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: str):
        """Sets the reason of this Reason.

        Defines a string object that is used for reason  # noqa: E501

        :param reason: The reason of this Reason.
        :type reason: str
        """
        if reason is None:
            raise ValueError("Invalid value for `reason`, must not be `None`")  # noqa: E501

        self._reason = reason
