# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TaskSubStates(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PENDING = "Pending"
    MOVING = "Moving"
    RETRIEVING = "Retrieving"
    RETRIEVED = "Retrieved"
    STORING = "Storing"
    STORED = "Stored"
    PARKING = "Parking"
    PARKED = "Parked"
    FAILED = "Failed"
    DONE = "Done"
    CANCELLED = "Cancelled"
    def __init__(self):  # noqa: E501
        """TaskSubStates - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TaskSubStates':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TaskSubStates of this TaskSubStates.  # noqa: E501
        :rtype: TaskSubStates
        """
        return util.deserialize_model(dikt, cls)
