# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TaskStates(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ENQUEUED = "Enqueued"
    REQUESTED = "Requested"
    ENROUTE = "Enroute"
    EXECUTING = "Executing"
    WAITING = "Waiting"
    SUSPENDED = "Suspended"
    FAILED = "Failed"
    ERRANT = "Errant"
    FINISHED = "Finished"
    CANCELLED = "Cancelled"
    def __init__(self):  # noqa: E501
        """TaskStates - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TaskStates':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TaskStates of this TaskStates.  # noqa: E501
        :rtype: TaskStates
        """
        return util.deserialize_model(dikt, cls)
