# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UnitSystems(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    METRIC = "Metric"
    BRITISH = "British"
    USA = "USA"
    def __init__(self):  # noqa: E501
        """UnitSystems - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'UnitSystems':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UnitSystems of this UnitSystems.  # noqa: E501
        :rtype: UnitSystems
        """
        return util.deserialize_model(dikt, cls)
